#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibriClassroom
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Google")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertLibriDepDean(LibriDepDean instance);
    partial void UpdateLibriDepDean(LibriDepDean instance);
    partial void DeleteLibriDepDean(LibriDepDean instance);
    partial void InsertKursiMeMateriale(KursiMeMateriale instance);
    partial void UpdateKursiMeMateriale(KursiMeMateriale instance);
    partial void DeleteKursiMeMateriale(KursiMeMateriale instance);
    partial void InsertFeed(Feed instance);
    partial void UpdateFeed(Feed instance);
    partial void DeleteFeed(Feed instance);
    partial void InsertReporting(Reporting instance);
    partial void UpdateReporting(Reporting instance);
    partial void DeleteReporting(Reporting instance);
    partial void InsertGoogleUser(GoogleUser instance);
    partial void UpdateGoogleUser(GoogleUser instance);
    partial void DeleteGoogleUser(GoogleUser instance);
    partial void InsertKursi(Kursi instance);
    partial void UpdateKursi(Kursi instance);
    partial void DeleteKursi(Kursi instance);
    partial void InsertCourseDelegation(CourseDelegation instance);
    partial void UpdateCourseDelegation(CourseDelegation instance);
    partial void DeleteCourseDelegation(CourseDelegation instance);
    partial void InsertCourseStat(CourseStat instance);
    partial void UpdateCourseStat(CourseStat instance);
    partial void DeleteCourseStat(CourseStat instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["GoogleConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<LibriDepDean> LibriDepDeans
		{
			get
			{
				return this.GetTable<LibriDepDean>();
			}
		}
		
		public System.Data.Linq.Table<KursiMeMateriale> KursiMeMateriales
		{
			get
			{
				return this.GetTable<KursiMeMateriale>();
			}
		}
		
		public System.Data.Linq.Table<Feed> Feeds
		{
			get
			{
				return this.GetTable<Feed>();
			}
		}
		
		public System.Data.Linq.Table<Reporting> Reportings
		{
			get
			{
				return this.GetTable<Reporting>();
			}
		}
		
		public System.Data.Linq.Table<GoogleUser> GoogleUsers
		{
			get
			{
				return this.GetTable<GoogleUser>();
			}
		}
		
		public System.Data.Linq.Table<Kursi> Kursis
		{
			get
			{
				return this.GetTable<Kursi>();
			}
		}
		
		public System.Data.Linq.Table<CourseDelegation> CourseDelegations
		{
			get
			{
				return this.GetTable<CourseDelegation>();
			}
		}
		
		public System.Data.Linq.Table<CourseStat> CourseStats
		{
			get
			{
				return this.GetTable<CourseStat>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LibriDepDean")]
	public partial class LibriDepDean : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _ID;
		
		private string _depname;
		
		private string _username;
		
		private string _deanname;
		
		private string _code;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(System.Guid value);
    partial void OnIDChanged();
    partial void OndepnameChanging(string value);
    partial void OndepnameChanged();
    partial void OnusernameChanging(string value);
    partial void OnusernameChanged();
    partial void OndeannameChanging(string value);
    partial void OndeannameChanged();
    partial void OncodeChanging(string value);
    partial void OncodeChanged();
    #endregion
		
		public LibriDepDean()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_depname", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string depname
		{
			get
			{
				return this._depname;
			}
			set
			{
				if ((this._depname != value))
				{
					this.OndepnameChanging(value);
					this.SendPropertyChanging();
					this._depname = value;
					this.SendPropertyChanged("depname");
					this.OndepnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username", DbType="NVarChar(100)")]
		public string username
		{
			get
			{
				return this._username;
			}
			set
			{
				if ((this._username != value))
				{
					this.OnusernameChanging(value);
					this.SendPropertyChanging();
					this._username = value;
					this.SendPropertyChanged("username");
					this.OnusernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_deanname", DbType="NVarChar(100)")]
		public string deanname
		{
			get
			{
				return this._deanname;
			}
			set
			{
				if ((this._deanname != value))
				{
					this.OndeannameChanging(value);
					this.SendPropertyChanging();
					this._deanname = value;
					this.SendPropertyChanged("deanname");
					this.OndeannameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_code", DbType="NVarChar(50)")]
		public string code
		{
			get
			{
				return this._code;
			}
			set
			{
				if ((this._code != value))
				{
					this.OncodeChanging(value);
					this.SendPropertyChanging();
					this._code = value;
					this.SendPropertyChanged("code");
					this.OncodeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KursiMeMateriale")]
	public partial class KursiMeMateriale : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _id;
		
		private System.Nullable<int> _jan;
		
		private System.Nullable<int> _feb;
		
		private System.Nullable<int> _mar;
		
		private System.Nullable<int> _apr;
		
		private System.Nullable<int> _may;
		
		private System.Nullable<int> _jun;
		
		private System.Nullable<int> _jul;
		
		private System.Nullable<int> _aug;
		
		private System.Nullable<int> _sep;
		
		private System.Nullable<int> _oct;
		
		private System.Nullable<int> _nov;
		
		private System.Nullable<int> _dec;
		
		private System.Guid _reportingid;
		
		private EntityRef<Reporting> _Reporting;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(System.Guid value);
    partial void OnidChanged();
    partial void OnjanChanging(System.Nullable<int> value);
    partial void OnjanChanged();
    partial void OnfebChanging(System.Nullable<int> value);
    partial void OnfebChanged();
    partial void OnmarChanging(System.Nullable<int> value);
    partial void OnmarChanged();
    partial void OnaprChanging(System.Nullable<int> value);
    partial void OnaprChanged();
    partial void OnmayChanging(System.Nullable<int> value);
    partial void OnmayChanged();
    partial void OnjunChanging(System.Nullable<int> value);
    partial void OnjunChanged();
    partial void OnjulChanging(System.Nullable<int> value);
    partial void OnjulChanged();
    partial void OnaugChanging(System.Nullable<int> value);
    partial void OnaugChanged();
    partial void OnsepChanging(System.Nullable<int> value);
    partial void OnsepChanged();
    partial void OnoctChanging(System.Nullable<int> value);
    partial void OnoctChanged();
    partial void OnnovChanging(System.Nullable<int> value);
    partial void OnnovChanged();
    partial void OndecChanging(System.Nullable<int> value);
    partial void OndecChanged();
    partial void OnreportingidChanging(System.Guid value);
    partial void OnreportingidChanged();
    #endregion
		
		public KursiMeMateriale()
		{
			this._Reporting = default(EntityRef<Reporting>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_jan", DbType="Int")]
		public System.Nullable<int> jan
		{
			get
			{
				return this._jan;
			}
			set
			{
				if ((this._jan != value))
				{
					this.OnjanChanging(value);
					this.SendPropertyChanging();
					this._jan = value;
					this.SendPropertyChanged("jan");
					this.OnjanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_feb", DbType="Int")]
		public System.Nullable<int> feb
		{
			get
			{
				return this._feb;
			}
			set
			{
				if ((this._feb != value))
				{
					this.OnfebChanging(value);
					this.SendPropertyChanging();
					this._feb = value;
					this.SendPropertyChanged("feb");
					this.OnfebChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mar", DbType="Int")]
		public System.Nullable<int> mar
		{
			get
			{
				return this._mar;
			}
			set
			{
				if ((this._mar != value))
				{
					this.OnmarChanging(value);
					this.SendPropertyChanging();
					this._mar = value;
					this.SendPropertyChanged("mar");
					this.OnmarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_apr", DbType="Int")]
		public System.Nullable<int> apr
		{
			get
			{
				return this._apr;
			}
			set
			{
				if ((this._apr != value))
				{
					this.OnaprChanging(value);
					this.SendPropertyChanging();
					this._apr = value;
					this.SendPropertyChanged("apr");
					this.OnaprChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_may", DbType="Int")]
		public System.Nullable<int> may
		{
			get
			{
				return this._may;
			}
			set
			{
				if ((this._may != value))
				{
					this.OnmayChanging(value);
					this.SendPropertyChanging();
					this._may = value;
					this.SendPropertyChanged("may");
					this.OnmayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_jun", DbType="Int")]
		public System.Nullable<int> jun
		{
			get
			{
				return this._jun;
			}
			set
			{
				if ((this._jun != value))
				{
					this.OnjunChanging(value);
					this.SendPropertyChanging();
					this._jun = value;
					this.SendPropertyChanged("jun");
					this.OnjunChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_jul", DbType="Int")]
		public System.Nullable<int> jul
		{
			get
			{
				return this._jul;
			}
			set
			{
				if ((this._jul != value))
				{
					this.OnjulChanging(value);
					this.SendPropertyChanging();
					this._jul = value;
					this.SendPropertyChanged("jul");
					this.OnjulChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_aug", DbType="Int")]
		public System.Nullable<int> aug
		{
			get
			{
				return this._aug;
			}
			set
			{
				if ((this._aug != value))
				{
					this.OnaugChanging(value);
					this.SendPropertyChanging();
					this._aug = value;
					this.SendPropertyChanged("aug");
					this.OnaugChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sep", DbType="Int")]
		public System.Nullable<int> sep
		{
			get
			{
				return this._sep;
			}
			set
			{
				if ((this._sep != value))
				{
					this.OnsepChanging(value);
					this.SendPropertyChanging();
					this._sep = value;
					this.SendPropertyChanged("sep");
					this.OnsepChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_oct", DbType="Int")]
		public System.Nullable<int> oct
		{
			get
			{
				return this._oct;
			}
			set
			{
				if ((this._oct != value))
				{
					this.OnoctChanging(value);
					this.SendPropertyChanging();
					this._oct = value;
					this.SendPropertyChanged("oct");
					this.OnoctChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nov", DbType="Int")]
		public System.Nullable<int> nov
		{
			get
			{
				return this._nov;
			}
			set
			{
				if ((this._nov != value))
				{
					this.OnnovChanging(value);
					this.SendPropertyChanging();
					this._nov = value;
					this.SendPropertyChanged("nov");
					this.OnnovChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dec", DbType="Int")]
		public System.Nullable<int> dec
		{
			get
			{
				return this._dec;
			}
			set
			{
				if ((this._dec != value))
				{
					this.OndecChanging(value);
					this.SendPropertyChanging();
					this._dec = value;
					this.SendPropertyChanged("dec");
					this.OndecChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_reportingid", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid reportingid
		{
			get
			{
				return this._reportingid;
			}
			set
			{
				if ((this._reportingid != value))
				{
					if (this._Reporting.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnreportingidChanging(value);
					this.SendPropertyChanging();
					this._reportingid = value;
					this.SendPropertyChanged("reportingid");
					this.OnreportingidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Reporting_KursiMeMateriale", Storage="_Reporting", ThisKey="reportingid", OtherKey="id", IsForeignKey=true)]
		public Reporting Reporting
		{
			get
			{
				return this._Reporting.Entity;
			}
			set
			{
				Reporting previousValue = this._Reporting.Entity;
				if (((previousValue != value) 
							|| (this._Reporting.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Reporting.Entity = null;
						previousValue.KursiMeMateriales.Remove(this);
					}
					this._Reporting.Entity = value;
					if ((value != null))
					{
						value.KursiMeMateriales.Add(this);
						this._reportingid = value.id;
					}
					else
					{
						this._reportingid = default(System.Guid);
					}
					this.SendPropertyChanged("Reporting");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Feed")]
	public partial class Feed : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _id;
		
		private string _courseId;
		
		private string _matSetName;
		
		private string _workType;
		
		private string _title;
		
		private string _description;
		
		private string _alternateLink;
		
		private System.Nullable<System.DateTime> _updateTime;
		
		private string _ThumbnailUrl;
		
		private string _ResponseUrl;
		
		private EntityRef<Kursi> _Kursi;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(string value);
    partial void OnidChanged();
    partial void OncourseIdChanging(string value);
    partial void OncourseIdChanged();
    partial void OnmatSetNameChanging(string value);
    partial void OnmatSetNameChanged();
    partial void OnworkTypeChanging(string value);
    partial void OnworkTypeChanged();
    partial void OntitleChanging(string value);
    partial void OntitleChanged();
    partial void OndescriptionChanging(string value);
    partial void OndescriptionChanged();
    partial void OnalternateLinkChanging(string value);
    partial void OnalternateLinkChanged();
    partial void OnupdateTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnupdateTimeChanged();
    partial void OnThumbnailUrlChanging(string value);
    partial void OnThumbnailUrlChanged();
    partial void OnResponseUrlChanging(string value);
    partial void OnResponseUrlChanged();
    #endregion
		
		public Feed()
		{
			this._Kursi = default(EntityRef<Kursi>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="NVarChar(150) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_courseId", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string courseId
		{
			get
			{
				return this._courseId;
			}
			set
			{
				if ((this._courseId != value))
				{
					if (this._Kursi.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OncourseIdChanging(value);
					this.SendPropertyChanging();
					this._courseId = value;
					this.SendPropertyChanged("courseId");
					this.OncourseIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_matSetName", DbType="NVarChar(MAX)")]
		public string matSetName
		{
			get
			{
				return this._matSetName;
			}
			set
			{
				if ((this._matSetName != value))
				{
					this.OnmatSetNameChanging(value);
					this.SendPropertyChanging();
					this._matSetName = value;
					this.SendPropertyChanged("matSetName");
					this.OnmatSetNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_workType", DbType="NVarChar(100)")]
		public string workType
		{
			get
			{
				return this._workType;
			}
			set
			{
				if ((this._workType != value))
				{
					this.OnworkTypeChanging(value);
					this.SendPropertyChanging();
					this._workType = value;
					this.SendPropertyChanged("workType");
					this.OnworkTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_title", DbType="NVarChar(150)")]
		public string title
		{
			get
			{
				return this._title;
			}
			set
			{
				if ((this._title != value))
				{
					this.OntitleChanging(value);
					this.SendPropertyChanging();
					this._title = value;
					this.SendPropertyChanged("title");
					this.OntitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_description", DbType="NVarChar(MAX)")]
		public string description
		{
			get
			{
				return this._description;
			}
			set
			{
				if ((this._description != value))
				{
					this.OndescriptionChanging(value);
					this.SendPropertyChanging();
					this._description = value;
					this.SendPropertyChanged("description");
					this.OndescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_alternateLink", DbType="NVarChar(150)")]
		public string alternateLink
		{
			get
			{
				return this._alternateLink;
			}
			set
			{
				if ((this._alternateLink != value))
				{
					this.OnalternateLinkChanging(value);
					this.SendPropertyChanging();
					this._alternateLink = value;
					this.SendPropertyChanged("alternateLink");
					this.OnalternateLinkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_updateTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> updateTime
		{
			get
			{
				return this._updateTime;
			}
			set
			{
				if ((this._updateTime != value))
				{
					this.OnupdateTimeChanging(value);
					this.SendPropertyChanging();
					this._updateTime = value;
					this.SendPropertyChanged("updateTime");
					this.OnupdateTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThumbnailUrl", DbType="NVarChar(150)")]
		public string ThumbnailUrl
		{
			get
			{
				return this._ThumbnailUrl;
			}
			set
			{
				if ((this._ThumbnailUrl != value))
				{
					this.OnThumbnailUrlChanging(value);
					this.SendPropertyChanging();
					this._ThumbnailUrl = value;
					this.SendPropertyChanged("ThumbnailUrl");
					this.OnThumbnailUrlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ResponseUrl", DbType="NVarChar(150)")]
		public string ResponseUrl
		{
			get
			{
				return this._ResponseUrl;
			}
			set
			{
				if ((this._ResponseUrl != value))
				{
					this.OnResponseUrlChanging(value);
					this.SendPropertyChanging();
					this._ResponseUrl = value;
					this.SendPropertyChanged("ResponseUrl");
					this.OnResponseUrlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Kursi_Feed", Storage="_Kursi", ThisKey="courseId", OtherKey="id", IsForeignKey=true)]
		public Kursi Kursi
		{
			get
			{
				return this._Kursi.Entity;
			}
			set
			{
				Kursi previousValue = this._Kursi.Entity;
				if (((previousValue != value) 
							|| (this._Kursi.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Kursi.Entity = null;
						previousValue.Feeds.Remove(this);
					}
					this._Kursi.Entity = value;
					if ((value != null))
					{
						value.Feeds.Add(this);
						this._courseId = value.id;
					}
					else
					{
						this._courseId = default(string);
					}
					this.SendPropertyChanged("Kursi");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Reporting")]
	public partial class Reporting : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _id;
		
		private System.Nullable<int> _perqindjaKurseveMeMateriale;
		
		private System.Nullable<int> _totalMateriale;
		
		private System.Nullable<int> _totalMaterialeJavaFundit;
		
		private System.Nullable<int> _totalDetyra;
		
		private System.Nullable<int> _totalDetyraJavaFundit;
		
		private System.Nullable<int> _totalLende;
		
		private System.Nullable<int> _totalLendePaMateriale;
		
		private System.Nullable<int> _nrLendeMeSyllPaMat;
		
		private System.Nullable<System.DateTime> _timeStamp;
		
		private string _department;
		
		private string _termid;
		
		private EntitySet<KursiMeMateriale> _KursiMeMateriales;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(System.Guid value);
    partial void OnidChanged();
    partial void OnperqindjaKurseveMeMaterialeChanging(System.Nullable<int> value);
    partial void OnperqindjaKurseveMeMaterialeChanged();
    partial void OntotalMaterialeChanging(System.Nullable<int> value);
    partial void OntotalMaterialeChanged();
    partial void OntotalMaterialeJavaFunditChanging(System.Nullable<int> value);
    partial void OntotalMaterialeJavaFunditChanged();
    partial void OntotalDetyraChanging(System.Nullable<int> value);
    partial void OntotalDetyraChanged();
    partial void OntotalDetyraJavaFunditChanging(System.Nullable<int> value);
    partial void OntotalDetyraJavaFunditChanged();
    partial void OntotalLendeChanging(System.Nullable<int> value);
    partial void OntotalLendeChanged();
    partial void OntotalLendePaMaterialeChanging(System.Nullable<int> value);
    partial void OntotalLendePaMaterialeChanged();
    partial void OnnrLendeMeSyllPaMatChanging(System.Nullable<int> value);
    partial void OnnrLendeMeSyllPaMatChanged();
    partial void OntimeStampChanging(System.Nullable<System.DateTime> value);
    partial void OntimeStampChanged();
    partial void OndepartmentChanging(string value);
    partial void OndepartmentChanged();
    partial void OntermidChanging(string value);
    partial void OntermidChanged();
    #endregion
		
		public Reporting()
		{
			this._KursiMeMateriales = new EntitySet<KursiMeMateriale>(new Action<KursiMeMateriale>(this.attach_KursiMeMateriales), new Action<KursiMeMateriale>(this.detach_KursiMeMateriales));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_perqindjaKurseveMeMateriale", DbType="Int")]
		public System.Nullable<int> perqindjaKurseveMeMateriale
		{
			get
			{
				return this._perqindjaKurseveMeMateriale;
			}
			set
			{
				if ((this._perqindjaKurseveMeMateriale != value))
				{
					this.OnperqindjaKurseveMeMaterialeChanging(value);
					this.SendPropertyChanging();
					this._perqindjaKurseveMeMateriale = value;
					this.SendPropertyChanged("perqindjaKurseveMeMateriale");
					this.OnperqindjaKurseveMeMaterialeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_totalMateriale", DbType="Int")]
		public System.Nullable<int> totalMateriale
		{
			get
			{
				return this._totalMateriale;
			}
			set
			{
				if ((this._totalMateriale != value))
				{
					this.OntotalMaterialeChanging(value);
					this.SendPropertyChanging();
					this._totalMateriale = value;
					this.SendPropertyChanged("totalMateriale");
					this.OntotalMaterialeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_totalMaterialeJavaFundit", DbType="Int")]
		public System.Nullable<int> totalMaterialeJavaFundit
		{
			get
			{
				return this._totalMaterialeJavaFundit;
			}
			set
			{
				if ((this._totalMaterialeJavaFundit != value))
				{
					this.OntotalMaterialeJavaFunditChanging(value);
					this.SendPropertyChanging();
					this._totalMaterialeJavaFundit = value;
					this.SendPropertyChanged("totalMaterialeJavaFundit");
					this.OntotalMaterialeJavaFunditChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_totalDetyra", DbType="Int")]
		public System.Nullable<int> totalDetyra
		{
			get
			{
				return this._totalDetyra;
			}
			set
			{
				if ((this._totalDetyra != value))
				{
					this.OntotalDetyraChanging(value);
					this.SendPropertyChanging();
					this._totalDetyra = value;
					this.SendPropertyChanged("totalDetyra");
					this.OntotalDetyraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_totalDetyraJavaFundit", DbType="Int")]
		public System.Nullable<int> totalDetyraJavaFundit
		{
			get
			{
				return this._totalDetyraJavaFundit;
			}
			set
			{
				if ((this._totalDetyraJavaFundit != value))
				{
					this.OntotalDetyraJavaFunditChanging(value);
					this.SendPropertyChanging();
					this._totalDetyraJavaFundit = value;
					this.SendPropertyChanged("totalDetyraJavaFundit");
					this.OntotalDetyraJavaFunditChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_totalLende", DbType="Int")]
		public System.Nullable<int> totalLende
		{
			get
			{
				return this._totalLende;
			}
			set
			{
				if ((this._totalLende != value))
				{
					this.OntotalLendeChanging(value);
					this.SendPropertyChanging();
					this._totalLende = value;
					this.SendPropertyChanged("totalLende");
					this.OntotalLendeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_totalLendePaMateriale", DbType="Int")]
		public System.Nullable<int> totalLendePaMateriale
		{
			get
			{
				return this._totalLendePaMateriale;
			}
			set
			{
				if ((this._totalLendePaMateriale != value))
				{
					this.OntotalLendePaMaterialeChanging(value);
					this.SendPropertyChanging();
					this._totalLendePaMateriale = value;
					this.SendPropertyChanged("totalLendePaMateriale");
					this.OntotalLendePaMaterialeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nrLendeMeSyllPaMat", DbType="Int")]
		public System.Nullable<int> nrLendeMeSyllPaMat
		{
			get
			{
				return this._nrLendeMeSyllPaMat;
			}
			set
			{
				if ((this._nrLendeMeSyllPaMat != value))
				{
					this.OnnrLendeMeSyllPaMatChanging(value);
					this.SendPropertyChanging();
					this._nrLendeMeSyllPaMat = value;
					this.SendPropertyChanged("nrLendeMeSyllPaMat");
					this.OnnrLendeMeSyllPaMatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_timeStamp", DbType="DateTime")]
		public System.Nullable<System.DateTime> timeStamp
		{
			get
			{
				return this._timeStamp;
			}
			set
			{
				if ((this._timeStamp != value))
				{
					this.OntimeStampChanging(value);
					this.SendPropertyChanging();
					this._timeStamp = value;
					this.SendPropertyChanged("timeStamp");
					this.OntimeStampChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_department", DbType="NVarChar(1)")]
		public string department
		{
			get
			{
				return this._department;
			}
			set
			{
				if ((this._department != value))
				{
					this.OndepartmentChanging(value);
					this.SendPropertyChanging();
					this._department = value;
					this.SendPropertyChanged("department");
					this.OndepartmentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_termid", DbType="NVarChar(10)")]
		public string termid
		{
			get
			{
				return this._termid;
			}
			set
			{
				if ((this._termid != value))
				{
					this.OntermidChanging(value);
					this.SendPropertyChanging();
					this._termid = value;
					this.SendPropertyChanged("termid");
					this.OntermidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Reporting_KursiMeMateriale", Storage="_KursiMeMateriales", ThisKey="id", OtherKey="reportingid")]
		public EntitySet<KursiMeMateriale> KursiMeMateriales
		{
			get
			{
				return this._KursiMeMateriales;
			}
			set
			{
				this._KursiMeMateriales.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_KursiMeMateriales(KursiMeMateriale entity)
		{
			this.SendPropertyChanging();
			entity.Reporting = this;
		}
		
		private void detach_KursiMeMateriales(KursiMeMateriale entity)
		{
			this.SendPropertyChanging();
			entity.Reporting = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.GoogleUser")]
	public partial class GoogleUser : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _GoogleID;
		
		private string _Username;
		
		private string _Fullname;
		
		private string _depid;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnGoogleIDChanging(string value);
    partial void OnGoogleIDChanged();
    partial void OnUsernameChanging(string value);
    partial void OnUsernameChanged();
    partial void OnFullnameChanging(string value);
    partial void OnFullnameChanged();
    partial void OndepidChanging(string value);
    partial void OndepidChanged();
    #endregion
		
		public GoogleUser()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GoogleID", DbType="NVarChar(150)")]
		public string GoogleID
		{
			get
			{
				return this._GoogleID;
			}
			set
			{
				if ((this._GoogleID != value))
				{
					this.OnGoogleIDChanging(value);
					this.SendPropertyChanging();
					this._GoogleID = value;
					this.SendPropertyChanged("GoogleID");
					this.OnGoogleIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Username", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Username
		{
			get
			{
				return this._Username;
			}
			set
			{
				if ((this._Username != value))
				{
					this.OnUsernameChanging(value);
					this.SendPropertyChanging();
					this._Username = value;
					this.SendPropertyChanged("Username");
					this.OnUsernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fullname", DbType="NVarChar(150)")]
		public string Fullname
		{
			get
			{
				return this._Fullname;
			}
			set
			{
				if ((this._Fullname != value))
				{
					this.OnFullnameChanging(value);
					this.SendPropertyChanging();
					this._Fullname = value;
					this.SendPropertyChanged("Fullname");
					this.OnFullnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_depid", DbType="NVarChar(1)")]
		public string depid
		{
			get
			{
				return this._depid;
			}
			set
			{
				if ((this._depid != value))
				{
					this.OndepidChanging(value);
					this.SendPropertyChanging();
					this._depid = value;
					this.SendPropertyChanged("depid");
					this.OndepidChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Kursi")]
	public partial class Kursi : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _id;
		
		private string _title;
		
		private string _coursecode;
		
		private System.DateTime _updatetime;
		
		private string _ownerid;
		
		private string _termid;
		
		private string _depid;
		
		private string _link;
		
		private string _username;
		
		private string _EnrollmentCode;
		
		private EntitySet<Feed> _Feeds;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(string value);
    partial void OnidChanged();
    partial void OntitleChanging(string value);
    partial void OntitleChanged();
    partial void OncoursecodeChanging(string value);
    partial void OncoursecodeChanged();
    partial void OnupdatetimeChanging(System.DateTime value);
    partial void OnupdatetimeChanged();
    partial void OnowneridChanging(string value);
    partial void OnowneridChanged();
    partial void OntermidChanging(string value);
    partial void OntermidChanged();
    partial void OndepidChanging(string value);
    partial void OndepidChanged();
    partial void OnlinkChanging(string value);
    partial void OnlinkChanged();
    partial void OnusernameChanging(string value);
    partial void OnusernameChanged();
    partial void OnEnrollmentCodeChanging(string value);
    partial void OnEnrollmentCodeChanged();
    #endregion
		
		public Kursi()
		{
			this._Feeds = new EntitySet<Feed>(new Action<Feed>(this.attach_Feeds), new Action<Feed>(this.detach_Feeds));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="NVarChar(200) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_title", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string title
		{
			get
			{
				return this._title;
			}
			set
			{
				if ((this._title != value))
				{
					this.OntitleChanging(value);
					this.SendPropertyChanging();
					this._title = value;
					this.SendPropertyChanged("title");
					this.OntitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_coursecode", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string coursecode
		{
			get
			{
				return this._coursecode;
			}
			set
			{
				if ((this._coursecode != value))
				{
					this.OncoursecodeChanging(value);
					this.SendPropertyChanging();
					this._coursecode = value;
					this.SendPropertyChanged("coursecode");
					this.OncoursecodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_updatetime", DbType="DateTime NOT NULL")]
		public System.DateTime updatetime
		{
			get
			{
				return this._updatetime;
			}
			set
			{
				if ((this._updatetime != value))
				{
					this.OnupdatetimeChanging(value);
					this.SendPropertyChanging();
					this._updatetime = value;
					this.SendPropertyChanged("updatetime");
					this.OnupdatetimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ownerid", DbType="NVarChar(150)")]
		public string ownerid
		{
			get
			{
				return this._ownerid;
			}
			set
			{
				if ((this._ownerid != value))
				{
					this.OnowneridChanging(value);
					this.SendPropertyChanging();
					this._ownerid = value;
					this.SendPropertyChanged("ownerid");
					this.OnowneridChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_termid", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string termid
		{
			get
			{
				return this._termid;
			}
			set
			{
				if ((this._termid != value))
				{
					this.OntermidChanging(value);
					this.SendPropertyChanging();
					this._termid = value;
					this.SendPropertyChanged("termid");
					this.OntermidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_depid", DbType="NVarChar(1)")]
		public string depid
		{
			get
			{
				return this._depid;
			}
			set
			{
				if ((this._depid != value))
				{
					this.OndepidChanging(value);
					this.SendPropertyChanging();
					this._depid = value;
					this.SendPropertyChanged("depid");
					this.OndepidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_link", DbType="NVarChar(100)")]
		public string link
		{
			get
			{
				return this._link;
			}
			set
			{
				if ((this._link != value))
				{
					this.OnlinkChanging(value);
					this.SendPropertyChanging();
					this._link = value;
					this.SendPropertyChanged("link");
					this.OnlinkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username", DbType="NVarChar(50)")]
		public string username
		{
			get
			{
				return this._username;
			}
			set
			{
				if ((this._username != value))
				{
					this.OnusernameChanging(value);
					this.SendPropertyChanging();
					this._username = value;
					this.SendPropertyChanged("username");
					this.OnusernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EnrollmentCode", DbType="NVarChar(100)")]
		public string EnrollmentCode
		{
			get
			{
				return this._EnrollmentCode;
			}
			set
			{
				if ((this._EnrollmentCode != value))
				{
					this.OnEnrollmentCodeChanging(value);
					this.SendPropertyChanging();
					this._EnrollmentCode = value;
					this.SendPropertyChanged("EnrollmentCode");
					this.OnEnrollmentCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Kursi_Feed", Storage="_Feeds", ThisKey="id", OtherKey="courseId")]
		public EntitySet<Feed> Feeds
		{
			get
			{
				return this._Feeds;
			}
			set
			{
				this._Feeds.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Feeds(Feed entity)
		{
			this.SendPropertyChanging();
			entity.Kursi = this;
		}
		
		private void detach_Feeds(Feed entity)
		{
			this.SendPropertyChanging();
			entity.Kursi = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CourseDelegation")]
	public partial class CourseDelegation : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _id;
		
		private string _kursiid;
		
		private string _userid;
		
		private string _username;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(System.Guid value);
    partial void OnidChanged();
    partial void OnkursiidChanging(string value);
    partial void OnkursiidChanged();
    partial void OnuseridChanging(string value);
    partial void OnuseridChanged();
    partial void OnusernameChanging(string value);
    partial void OnusernameChanged();
    #endregion
		
		public CourseDelegation()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kursiid", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string kursiid
		{
			get
			{
				return this._kursiid;
			}
			set
			{
				if ((this._kursiid != value))
				{
					this.OnkursiidChanging(value);
					this.SendPropertyChanging();
					this._kursiid = value;
					this.SendPropertyChanged("kursiid");
					this.OnkursiidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userid", DbType="NVarChar(50)")]
		public string userid
		{
			get
			{
				return this._userid;
			}
			set
			{
				if ((this._userid != value))
				{
					this.OnuseridChanging(value);
					this.SendPropertyChanging();
					this._userid = value;
					this.SendPropertyChanged("userid");
					this.OnuseridChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username", DbType="NVarChar(200)")]
		public string username
		{
			get
			{
				return this._username;
			}
			set
			{
				if ((this._username != value))
				{
					this.OnusernameChanging(value);
					this.SendPropertyChanging();
					this._username = value;
					this.SendPropertyChanged("username");
					this.OnusernameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CourseStats")]
	public partial class CourseStat : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _id;
		
		private string _courseId;
		
		private string _userid;
		
		private System.Nullable<int> _nrStudents;
		
		private System.Nullable<bool> _hasSyllabus;
		
		private System.Nullable<bool> _hasResources;
		
		private System.Nullable<bool> _hasAssignments;
		
		private System.Nullable<int> _nrResources;
		
		private System.Nullable<int> _nrAssignments;
		
		private System.Nullable<int> _nrStreams;
		
		private System.Nullable<int> _courseLevel;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(System.Guid value);
    partial void OnidChanged();
    partial void OncourseIdChanging(string value);
    partial void OncourseIdChanged();
    partial void OnuseridChanging(string value);
    partial void OnuseridChanged();
    partial void OnnrStudentsChanging(System.Nullable<int> value);
    partial void OnnrStudentsChanged();
    partial void OnhasSyllabusChanging(System.Nullable<bool> value);
    partial void OnhasSyllabusChanged();
    partial void OnhasResourcesChanging(System.Nullable<bool> value);
    partial void OnhasResourcesChanged();
    partial void OnhasAssignmentsChanging(System.Nullable<bool> value);
    partial void OnhasAssignmentsChanged();
    partial void OnnrResourcesChanging(System.Nullable<int> value);
    partial void OnnrResourcesChanged();
    partial void OnnrAssignmentsChanging(System.Nullable<int> value);
    partial void OnnrAssignmentsChanged();
    partial void OnnrStreamsChanging(System.Nullable<int> value);
    partial void OnnrStreamsChanged();
    partial void OncourseLevelChanging(System.Nullable<int> value);
    partial void OncourseLevelChanged();
    #endregion
		
		public CourseStat()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_courseId", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string courseId
		{
			get
			{
				return this._courseId;
			}
			set
			{
				if ((this._courseId != value))
				{
					this.OncourseIdChanging(value);
					this.SendPropertyChanging();
					this._courseId = value;
					this.SendPropertyChanged("courseId");
					this.OncourseIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userid", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string userid
		{
			get
			{
				return this._userid;
			}
			set
			{
				if ((this._userid != value))
				{
					this.OnuseridChanging(value);
					this.SendPropertyChanging();
					this._userid = value;
					this.SendPropertyChanged("userid");
					this.OnuseridChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nrStudents", DbType="Int")]
		public System.Nullable<int> nrStudents
		{
			get
			{
				return this._nrStudents;
			}
			set
			{
				if ((this._nrStudents != value))
				{
					this.OnnrStudentsChanging(value);
					this.SendPropertyChanging();
					this._nrStudents = value;
					this.SendPropertyChanged("nrStudents");
					this.OnnrStudentsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hasSyllabus", DbType="Bit")]
		public System.Nullable<bool> hasSyllabus
		{
			get
			{
				return this._hasSyllabus;
			}
			set
			{
				if ((this._hasSyllabus != value))
				{
					this.OnhasSyllabusChanging(value);
					this.SendPropertyChanging();
					this._hasSyllabus = value;
					this.SendPropertyChanged("hasSyllabus");
					this.OnhasSyllabusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hasResources", DbType="Bit")]
		public System.Nullable<bool> hasResources
		{
			get
			{
				return this._hasResources;
			}
			set
			{
				if ((this._hasResources != value))
				{
					this.OnhasResourcesChanging(value);
					this.SendPropertyChanging();
					this._hasResources = value;
					this.SendPropertyChanged("hasResources");
					this.OnhasResourcesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hasAssignments", DbType="Bit")]
		public System.Nullable<bool> hasAssignments
		{
			get
			{
				return this._hasAssignments;
			}
			set
			{
				if ((this._hasAssignments != value))
				{
					this.OnhasAssignmentsChanging(value);
					this.SendPropertyChanging();
					this._hasAssignments = value;
					this.SendPropertyChanged("hasAssignments");
					this.OnhasAssignmentsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nrResources", DbType="Int")]
		public System.Nullable<int> nrResources
		{
			get
			{
				return this._nrResources;
			}
			set
			{
				if ((this._nrResources != value))
				{
					this.OnnrResourcesChanging(value);
					this.SendPropertyChanging();
					this._nrResources = value;
					this.SendPropertyChanged("nrResources");
					this.OnnrResourcesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nrAssignments", DbType="Int")]
		public System.Nullable<int> nrAssignments
		{
			get
			{
				return this._nrAssignments;
			}
			set
			{
				if ((this._nrAssignments != value))
				{
					this.OnnrAssignmentsChanging(value);
					this.SendPropertyChanging();
					this._nrAssignments = value;
					this.SendPropertyChanged("nrAssignments");
					this.OnnrAssignmentsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nrStreams", DbType="Int")]
		public System.Nullable<int> nrStreams
		{
			get
			{
				return this._nrStreams;
			}
			set
			{
				if ((this._nrStreams != value))
				{
					this.OnnrStreamsChanging(value);
					this.SendPropertyChanging();
					this._nrStreams = value;
					this.SendPropertyChanged("nrStreams");
					this.OnnrStreamsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_courseLevel", DbType="Int")]
		public System.Nullable<int> courseLevel
		{
			get
			{
				return this._courseLevel;
			}
			set
			{
				if ((this._courseLevel != value))
				{
					this.OncourseLevelChanging(value);
					this.SendPropertyChanging();
					this._courseLevel = value;
					this.SendPropertyChanged("courseLevel");
					this.OncourseLevelChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
